server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;

    location = /b {
        return 301 /;
    }

    location = /impressum {
        try_files /impressum.html =404;
    }

    location = /datenschutz {
        try_files /datenschutz.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
